# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Runs unit tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build"
  lane :build do
    gradle(task: "clean assembleRelease")
  end

  desc "Send new Beta Release to Firebase App Distribution"
  lane :beta do
    build(type: "release", task: "assemble")

    firebase_app_distribution(
        app: "1:125522440221:android:797b339b46c32b3f2616f4",
        testers: "ezichukwuamarachi@gmail.com, vivian.morenikenji@gmail.com",
        release_notes: "OCS Android Development Assessment"
    )
  end

end
